version: 2.1
workflows:
  version: 2
  ruby-exclaim:
    jobs:
      - build:
          context: Salsify
jobs:
  build:
    docker:
      - image: salsify/ruby_ci:2.7.2
    environment:
      RACK_ENV: "test"
      RAILS_ENV: "test"
      CIRCLE_TEST_REPORTS: "test-results"
    working_directory: ~/ruby-exclaim
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-gems-ruby-2.7.2-{{ checksum "ruby-exclaim.gemspec" }}-{{ checksum "Gemfile" }}
            - v1-gems-ruby-2.7.2-
      - run:
          name: Install Gems
          command: |
            if ! bundle check --path=vendor/bundle; then
              bundle install --path=vendor/bundle --jobs=4 --retry=3
              bundle clean
            fi
      - save_cache:
          key: v1-gems-ruby-2.7.2-{{ checksum "ruby-exclaim.gemspec" }}-{{ checksum "Gemfile" }}
          paths:
            - "vendor/bundle"
            - "gemfiles/vendor/bundle"
      - run:
          name: Run Rubocop
          command: bundle exec rubocop
      - run:
          name: Run Tests
          command: |
            bundle exec rspec --format RspecJunitFormatter --out $CIRCLE_TEST_REPORTS/rspec/junit.xml --format progress spec
      - store_test_results:
          path: "test-results"
